### ISSUE TITLE
Fetch default region from .aws/config

### ISSUE THREAD

**Issue by ukch** [kubek2k/lambdoku#10]
I have my AWS config/credentials stored in the files `~/.aws/config` and `~/.aws/credentials`. If I don't have the `AWS_*` environment variables set, I would expect the relevant details to be found in those files instead.

It seems the credentials are being found in the file, as expected, but the default region is not pulled from the `config` file.

The contents of my `~/.aws/config` is as follows:
```
[default]
region = eu-west-1
```

**Comment by kubek2k** [comment]
Thats a bit 🐟 'y with aws-sdk for js. It appears that this should work for `aws-cli`: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html#cli-quick-configuration and AWS SDK for java: http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-region-selection.html, but not for aws-sdk for js. I could bypass that by adding custom code that would handle `.aws/config` reading, but it seems like Amazon should fix it on their side.

**Comment by kubek2k** [comment]
Ah - as a side note - I could also hardcode the default region to eg. 'eu-west-1', assuming that everyone uses ARN's instead of lambdaNames which may be prone to mistakes.

**Comment by kubek2k** [comment]
they are working on this it appears: https://github.com/aws/aws-sdk-js/issues/1039

**Comment by shockwavemoto** [comment]
>I have my AWS config/credentials stored in the files ~/.aws/config and ~/.aws/credentials. If I don't have the AWS_* environment variables set, I would expect the relevant details to be found in those files instead.
It seems the credentials are being found in the file, as expected, but the default region is not pulled from the config file.
The contents of my ~/.aws/config is as follows:
[default]
region = eu-west-1

You have to do aws config to change the region

**Comment by kubek2k** [comment]
it seems to be addressed in PR: https://github.com/aws/aws-sdk-js/pull/1391. I will update dependencies and see if it works.
