### ISSUE TITLE
why not http://apex.run/ ? EOM

### ISSUE THREAD

**Issue by mnugumanova** [kubek2k/lambdoku#7]

**Comment by kubek2k** [comment]
hi @ilmiran - I really ❤️  the work that has been done in apex, but I wanted something totally different - simpler tooling that is not infecting the software we create in any way. My main point of creating this was actually to improve the CD-like working that we do in our company. The idea is that our CI server deploys the lambda to dev instance and developer is able to promote the software when he thinks its time.

all the best
